// packages/frontend/src/components/pages/Login.tsx
import { LoginForm } from '../organisms/LoginForm';
import React from 'react';
import Logo from '../../assets/logo/clug-logo-w.svg';
import '../atoms/logo.scss';

export const Login = () => {
  return (
    <>
      <img src={Logo} alt="Clug logo" className="login-logo"/>
      <LoginForm />
    </>
  );
};

// packages/frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';


@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: [ './login.component.scss' ]
})
export class LoginComponent {
}

<div class="login">
  <div class="login__container">
    <img class="login__img" src="/assets/logo/clug-logo-w.svg" alt="logo clug">
    <p class="login__slogan" i18n="login slogan made by marketing professionals@@loginSlogan">Log in and manage your club!</p>
    <app-login-form></app-login-form>
  </div>
</div>
